Feature/sessionId_value&testcode
corca-ai/adcio_android_plugins pull request #25
Opened 2023-09-15 07:38 UTC by aahspringaa4

sessionId의 갑 관리하는 방식을 앱이 생존하는 동안 유지되도록 바꿨습니다.
그에 대한 테스트 코드를 작성했습니다

2023-09-15 07:53 UTC, adbr-dev requested changes

2023-09-15 07:53 UTC, adbr-dev commented on adcio_core/src/androidTest/java/com/corcaai/TestSessionIdManage.kt
> +    fun testSessionIdPersistence() {
테스트 코드 메세지가 없기도 하고 
만약 테스트를 함수명 기반으로 따진다고 하면 이름이 직관적이지않아요

2023-09-15 07:53 UTC, adbr-dev commented on adcio_core/src/androidTest/java/com/corcaai/TestSessionIdManage.kt
> +        // 잠시 대기하여 시간이 경과하도록 함 (예: 1초)
ㄴㄴ 한글 주석 다 빼세요

2023-09-15 07:53 UTC, adbr-dev commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
> +    private var sessionIdValue: String? = null
value라고 별도로 변수명 짓는거 말고 private, public이랑 잘 쓸 수 있는 좋은 방법 없을까요?

2023-09-15 07:53 UTC, adbr-dev commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
> +            return sessionIdValue!!
!! 가 not null 을 뜻하는건가요?

2023-09-15 07:56 UTC, aahspringaa4 commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
> +            return sessionIdValue!!
네!

2023-09-15 07:57 UTC, aahspringaa4 commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
> +    private var sessionIdValue: String? = null
흠.. sessionId의 값을 들고 있다가 주입할때 쓰는 변수라서 Value라고 쓰긴했는데 고민해 보겠습니다

2023-09-15 08:13 UTC, aahspringaa4 commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
> +            return sessionIdValue!!
nullable이라서 안쓰면 코틀린은 null을 허용하지 않기 때문에 오류가 나지만 그 전에 null 일 경우에 값을 할당하기 때문에 문제 없습니다!

2023-09-15 08:24 UTC, adbr-dev requested changes

2023-09-15 08:24 UTC, adbr-dev commented on adcio_agent/src/main/java/ai/corca/adcio_agent/provider/AdcioAgent.kt
> +        val agentUrl = "$baseUrl/${AdcioInfo.clientId}/$startPage?platform=android&show_appbar=$showAppBar"
클라이언트 Id 입력이 없을 때 AdcioCore.clientId 할당해주는 코드로 변경해주세요

2023-09-15 08:25 UTC, adbr-dev requested changes

2023-09-15 08:25 UTC, adbr-dev commented on adcio_core/src/androidTest/java/com/corcaai/TestSessionIdManage.kt
> +    fun testIsSessionIdMatch() {
match 보다 same equals 와 같은 명칭이 낫지않을까요? 명명 직관성.. 너무 떨어지는데..

2023-09-18 02:35 UTC, adbr-dev requested changes
test code..가 어딨죠? 
adcio_core/src/test/java/com/corcaai/AdcioCoreUnitTest.kt
제가 보이는 테스트 코드 부분은 여기 뿐인데 맞나요?

2023-09-18 02:35 UTC, adbr-dev commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioCore.kt
> +            if (!isInitialized) throw NotInitializedException(notInitializedComment)
아래 sessionId, deticeId .. 등 모두 if문 통일성 맞춰주세요 
얘만 ! 부정문 묻고 exception throws 하는 식이네요

2023-09-18 02:35 UTC, adbr-dev commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioCore.kt
> +    private const val notInitializedComment: String = "You must call init before using the core."
NotInitializedException.kt 파일에 메세지 default로 적어주면 될 것 같아요 core 구현체 레벨에서 코멘트를 적을 필욘 없을 것 같아요

2023-09-18 02:37 UTC, adbr-dev requested changes

2023-09-18 02:37 UTC, adbr-dev commented on adcio_core/src/androidTest/java/com/corcaai/AdcioCoreInstrumentedTest.kt
파일 분리가 왜 되어있는거예요? 테스트 코드 test 별로 나눠서 메소드 분리해주세요

2023-09-18 02:40 UTC, aahspringaa4 commented
AndroidCreInstrumentedTest는 안드로이드 관점에서 테스트 하는 코드이고 Unit은 단순한 코틀린 테스트입니다.

2023-09-18 02:40 UTC, adbr-dev commented
테스트 코드 분명 최소 실패 케이스 4개 + 정상 케이스 4개 + sessionId, deviceID 동일한 값 검증 2개 = unit test 10개가 나와야되는데 파일 분리가 왜 되어있는지 모르겠고 한 파일에 10개 테스트 메소드 작성해주세요 4시전까지 제 컨펌은 없습니다 꼼꼼히 작업하고 두분이서 컨펌하시고 다음 작업 진행해주세요

2023-09-19 05:33 UTC, adbr-dev requested changes
거의 다왔어요! 한번만 더 수정합시다~

2023-09-19 05:33 UTC, adbr-dev commented on adcio_core/build.gradle.kts
> +    set("PUBLISH_DESCRIPTION", "ADCIO_Core")
```suggestion
    set("PUBLISH_DESCRIPTION", "adcio_core is adcio service library")
```

2023-09-19 05:33 UTC, adbr-dev commented on adcio_core/build.gradle.kts
> +    androidTestImplementation("androidx.test:core-ktx:1.5.0")
정렬 예쁘게 plz

2023-09-19 05:33 UTC, adbr-dev commented on adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioCore.kt
> +    fun init(id: String) {
init 명칭 통일화 할게요~ firebase_core에서 initializeApp로 초기화 하니 우리도 비슷하게 가겠습니다!
```suggestion
    fun initializeApp(id: String) {
```

2023-09-19 05:35 UTC, aahspringaa4 commented on adcio_core/build.gradle.kts
> +    set("PUBLISH_DESCRIPTION", "ADCIO_Core")
앗 다른 모듈들도 이런식으로 되어있는데 그럼 suggestion, agent 같은 모듈들에서 core 사용하는 방법으로 수정할때에 그 친구들도 조금만 더 친절하게 바꾸겠습니다!

2023-09-19 05:39 UTC, adbr-dev approved these changes
고생하셨습니당 :D ~

2023-09-19 05:40 UTC, merged