develop placement module
corca-ai/adcio_android_plugins pull request #3
Opened 2023-08-28 04:34 UTC by snack655

## :pushpin: Type of PR
feature

## :recycle: Current situation

## :bulb: Proposed solution

## :heavy_plus_sign: Additional Information

### :test_tube: Testing

### :technologist: Reviewer Nudging

### :books: TODO

2023-08-28 05:09 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
> +        return PlacementRemote().getSuggestion(
이 부분 필드로 빼기, 메모리 누수.

2023-08-28 08:24 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
> +        return PlacementRemote().getSuggestion(
[428725b](https://github.com/corca-ai/adcio_android_plugins/pull/3/commits/428725b1dda3a73b8dca1c8fb95e1bed5c1be80c) 해결

2023-08-28 08:32 UTC, aahspringaa4 requested changes
항상 민재님 코드는 배울점이 많을 것 같습니다!!

일단 보이는 부분 최대한 리뷰 남겼는데 민재님 리뷰 반영하시고 텍세 가시면 다시 한번 살펴보겠습니다!

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
> +    private val adcioInfo = AdcioSuggestionInfo()
이런 부분은 추후에 DI로 바꾸는 것도 나쁘지 않을것 같네요

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionMapper.kt
> +internal fun AdcioSuggestion.toAdcioSuggestionData(): AdcioSuggestionData = AdcioSuggestionData(
이렇게 줄 길어지면 :에서 띄우는것도 괜찮긴합니다.

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionRawMapper.kt
> +    suggestionsData = this.suggestions.map { it.toAdcioSuggestionData() }
근데 컨버팅 하실때 this가 필요했나요?

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionRawMapper.kt
> +    suggestionsData = this.suggestions.map { it.toAdcioSuggestionData() }
원래?

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
~Data는 변수 네이밍의 가독성이 약간 떨어지는것 같아요. 

suggestions로만으로도 변수 정보 전달은 가능할 것 같습니다

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/RetrofitClient.kt
> +    private var retrofit: Retrofit? = null
null 안정성을 위하여 nullable 보다는 lateinit은 어떤가욤?

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/PlacementMapper.kt
> +    else -> PropertyData.NEW
propertyData.이라는 코드가 반복되는데 apply 처리 할까요?

아 when 문안에서 안되나요?

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +        Log.d("TestLogLog", "Service : ${service.hashCode()}")
Log는 일부러 남겨주신건가요?

2023-08-28 08:32 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +    private val networkSuccessRange = 200 until 300
코틀린에는 .. 가 있긴합니다!

2023-08-28 08:35 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
> +    private val adcioInfo = AdcioSuggestionInfo()
리펙토링 업무 작업 리스트 만들어서 추가해 두었습니다!
https://www.notion.so/corcaai/8c1395e52191436da349ddada013ed09?pvs=4

2023-08-28 08:38 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionRawMapper.kt
> +    suggestionsData = this.suggestions.map { it.toAdcioSuggestionData() }
아니요 선택 사항입니다. 개인적으로 가독성이 더 편하다고 생각해서 확장함수 혹은 apply에 this를 작성하기는 하지만 많이 별로라면 빼는 작업 스근하게 하도록 하겠습니다.

2023-08-28 08:40 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
엇 그런데 placement, banner 이런식으로 해버리면 Model과의 네이밍 충돌로 인해서 오히려 가독성이 떨어질 것 같아요! retrofit에 Call객체와 Android Call 객체를 계속 분리해서 작성해야 하는 것 처럼 말이에요..

2023-08-28 08:42 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionRawMapper.kt
> +    suggestionsData = this.suggestions.map { it.toAdcioSuggestionData() }
이건 민재님 선택에 맡기겠습니다! 코드 스타일 같네요

2023-08-28 08:43 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
그럼 suggestionList 같은 닉은 어떤가요?

2023-08-28 08:43 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/PlacementMapper.kt
> +    else -> PropertyData.NEW
엇 넵..ㅠㅠ apply 되면 엄청 깔끔했을거 같은데 아쉽네요..

2023-08-28 08:44 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +        Log.d("TestLogLog", "Service : ${service.hashCode()}")
아하 맞네요! 지우겠습니다.

2023-08-28 08:44 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +    private val networkSuccessRange = 200 until 300
수정 완료했습니다.

2023-08-28 08:49 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/RetrofitClient.kt
> +    private var retrofit: Retrofit? = null
수정 완료했습니다.

[pref: retrofit entity to non nullable with lateinit](https://github.com/corca-ai/adcio_android_plugins/pull/3/commits/6724278182493eec9765efbe5147e0d4a7e581e2)

2023-08-28 08:50 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/mapper/AdcioSuggestionMapper.kt
> +internal fun AdcioSuggestion.toAdcioSuggestionData(): AdcioSuggestionData = AdcioSuggestionData(
[style: match code convention](https://github.com/corca-ai/adcio_android_plugins/pull/3/commits/17b9bc570355693f6e0d6d5426e483ef6c12e1c6)

수정 완료했습니다.

2023-08-28 08:51 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
어디까지나 suggestions만 해당되는 거 아닌가요??

2023-08-28 08:52 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
아하 맞네요! suggestions는 변경하는 것이 맞는거 같아요! 고유 객체가 아니라..

2023-08-28 08:53 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
suggestionDatas 어떤가요?

2023-08-28 10:18 UTC, snack655 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/AdcioSuggestionRawData.kt
> +    @SerializedName("suggestions") val suggestionsData: List<AdcioSuggestionData>,
수정 완료했습니다!

2023-08-29 01:22 UTC, aahspringaa4 approved these changes
Looks Good To Me 👍

2023-08-29 01:27 UTC, merged