ADCIO-1773) feat: update placement
corca-ai/adcio_android_plugins pull request #62
Opened 2023-11-22 06:12 UTC by aahspringaa4

placement에 생긴 API 변동사항을 반영합니다.

2023-12-14 02:50 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/exception/Error.kt
> +open class PlatformException(
이 PlatformException이 Android상에서 기본 Exception인건가요? 

Flutter상에선 PlatformException이 기본 Exception이기 때문에 상속받아서 code와 message를 상속받아 커스텀 에러를 생성한건데 여기선 이 코드가 불필요해보여요 toString()을 커스텀하는것도 초기 목적과 다른 것 같아요

2023-12-14 03:01 UTC, adbr-dev requested changes
다 못봤는데 아쉽게도 눈에 보이는 이슈 부분이 많네요
다시 정책이랑 swagger문서 보면서 동작해보면서 코드 다시 작성해주세요

2023-12-14 03:01 UTC, adbr-dev commented on adcio_placement/src/androidTest/java/ai/corca/adcio_placement/AdcioPlacementTest.kt
> +    fun testPlacementCallSuccess() {
요거 테스트 코드 when과 같은 이렇게 들어왔을 때 -> 이렇게 리턴할거다
라는 코드 expect같이 검증하는 코드만 있어서 물음표인딩 ..

제가 안드로이드 테스트코드를 참고할만한 자료가 있을까요? 

어떤걸 참고하고 작성해주신건지 자료 주시거나 위 질문에 when/verify같은 코드가 들어가는 부분을 설명 주시면 좋을 것 같아요

2023-12-14 03:01 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/RetrofitClient.kt
> +                message = 0
message 0..은 뭐죠..? 메세지 전달 없이 0이 뭔지 궁금합니다

2023-12-14 03:01 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/ErrorResponse.kt
이쪽 코드가 왜 필요할까용?

2023-12-14 03:01 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +        val exception = RetrofitClient.exceptionHandling(response)
이쪽 코드가 왜 필요한거졍..? exceptionHandling이 커스텀 함수여서 커스텀하게 묶을 필요가 있는지 궁금해요

2023-12-14 03:01 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +                errorMessage = "placementId must be a UUID"
message로 반환되는거 req/res 체크해봤나용? 저 메세지만 오는게 아닌데.. swagger보면서 기능과 명세 다시 잘 체크해주세요

2023-12-14 07:28 UTC, aahspringaa4 commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +                errorMessage = "placementId must be a UUID"
message는 Int 값으로 숫자만 오고 있는 것 확인하였습니당!

2023-12-15 05:13 UTC, adbr-dev requested changes

2023-12-15 05:13 UTC, adbr-dev commented on adcio_placement/src/androidTest/java/ai/corca/adcio_placement/AdcioPlacementTest.kt
오케이 when 코드는 알았는데 expect,verify같은 검증 코드는 왜 없쥬..?
아래 문서 참고해서 반영해보시쥬
https://www.devkuma.com/docs/kotlin/mockk/#%EB%A7%A4%EC%B9%AD-matchers

2023-12-15 05:13 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/exception/Error.kt
> +    val errorMessage: String = "placementId must be a UUID",
악 BadRequest placement UUID 체크만 하는게 아니라 모든 필드의 타입을 검증하는 코드예요 swagger문서보고 다시 실행 여러번 해보면서 API 파악부터 하고 코드 작성해주세요 ! 다시 작성 ㄱㄱ

2023-12-18 03:23 UTC, adbr-dev requested changes

2023-12-18 03:23 UTC, adbr-dev commented on adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
> +            400 -> BadRequestException()
message 파악해보셨나용? errorResponse.message 있을텐데 다 무시되고 있는 코드네요 ?

2023-12-18 04:55 UTC, adbr-dev submitted a review, later dismissed
굿 고생많았습니닷 릴리즈 부탁드려요 ~

2023-12-18 05:03 UTC, merged